language: php

php:
    - 7.2
    - 7.3
    - 7.4

notifications:
    email:
        on_success: never

before_script:
    - travis_retry composer self-update
    - travis_retry composer install

script:
    - composer run test

after_success: bash <(curl -s https://codecov.io/bash)
